hako-mikan/sd-webui-supermerger

scripts/mergers/model_util.py, scripts/supermerger.py
- Windows以外のOSでmbwpresets.txtの読み込みに失敗する問題の修正
- Windows以外のOSで保存時のディレクトリ名の取得に失敗する問題の修正
=> Support for linux style paths

install.py
Add install.py to automatically install dependencies.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions#installpy
=> Install dependencies with install.py

scripts/mergers/mergers.py
add a missing brace in the modelname
=> add a missing brace

README.md, scripts/mergers/mergers.py
=> metadate -> metadata

scripts/mergers/model_util.py
=> add dot to pre

scripts/mergers/mergers.py, scripts/supermerger.py
* imported from webui/modules/extras.py
=> support Bake VAE feature.

scripts/mergers/mergers.py, scripts/mergers/model_util.py
~~***WIP***~~ DONE
* imported from webui/modules/extras.py https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/44c46f0 by @automatic1111 and https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7240 by @Unstackd
----
=> WIP: support inpainting/pix2pix merging.

scripts/mergers/xyplot.py
The conditional for seed and plot types.
Fixes #129 for me
Hope it is useful for others.
=> Missed brackets

scripts/supermerger.py
=> refresh presets

scripts/mergers/xyplot.py, scripts/supermerger.py
This should fix misalignment of label and member of Reserve XY Plot list.
=> Fix misalignment of Reserve XY Plot list

scripts/mergers/mergers.py, scripts/supermerger.py
Added multithread version of smoothAdd.
Number of max concurrent threads is decided by the result of cpu_count().
=> Add multithread version of smoothAdd

scripts/mergers/mergers.py, scripts/mergers/xyplot.py
It was dirty copy-pasted from here:
https://stackoverflow.com/questions/287871/how-do-i-print-colored-text-to-the-terminal
I'm really not sure if it is errors free but it works and it might be useful for others.
=> Colored print

scripts/supermerger.py, style.css
support set(reset), add and mul block level weights. Please see the following screenshot.
=> add block level weights set/add/mul

scripts/mergers/bcolors.py, scripts/mergers/mergers.py, scripts/mergers/xyplot.py
=> Moved colors to a file

scripts/supermerger.py
~~this is a quick hack to~~ support partial history loading
=> support partial history loading

scripts/supermerger.py, style.css
hide alpha/beta visibility when "use MBW" is checked.
=> Misc UI fixes

scripts/mergers/mergers.py
it solves the following issues.
- correct `Model:` name as "`Brav6 x 0.8 + aniverse_V12Pruned x 0.2`" with txt2img/img2img tabs
- different `Model hash:` (fake hash)
=> minimal checkpoint_info fix

scripts/mergers/model_util.py
call `send_model_to_trash()` at the `usemodel_in()` solve this issue
=> fix cuda memory issue for sd-webui-v1.6.0

scripts/supermerger.py
* only model of `model_a` component is checked.
* show `isxl` if `ckpt` file is used.
=> auto detect SDXL

README.md, scripts/mergers/mergers.py, scripts/mergers/pluslora.py, scripts/supermerger.py
Reverts hako-mikan/sd-webui-supermerger#203
=> Revert "auto detect SDXL"

scripts/supermerger.py
=> fix text2slider() to support SDXL

scripts/mergers/mergers.py, scripts/supermerger.py
=> add Adjust (Fine tune) UI

scripts/mergers/mergers.py
fix `fake_checkpoint_info()` to support v1.5.0-RC and above
=> fix fake_checkpoint_info() for v1.5.x

scripts/supermerger.py
fix regression bug introduced by #226 commit 937324a1f8f2bbf085
=> fix regression bug

scripts/supermerger.py
~~***WIP***~~
UI rearranging, and so on...
Any suggestions are welcome. ~~(will post screenshots as soon as possible)~~
=> UI tune up

scripts/supermerger.py
* fix dropdown labels
* call `lora.list_available_loras` correctly
=> fix Elements tab

scripts/mergers/pluslora.py
speed up dimension, alpha calculation by searching safetensors header
- original method: 496 LoRA(with ~37 Locon) - takes ~4min13sec
- using this fix: 496 LoRA(with ~37 Locon) - takes only ~14sec
=> speed up dimension,alpha calculation of LoRA/Locon

scripts/mergers/mergers.py
for #230 
Corrected code and moved a bit
=> Small correction to set ModC=ModA

scripts/supermerger.py
=> update adjust settings ui

scripts/supermerger.py
Added a refresh button and sorting to the presets dropdown. 
Replaced the naming field with custom input to the dropdown, which makes it a bit easier to select items for deletion/overwriting. 
Replaced the save mode checkbox group with an overwrite toggle and delete button.
An empty xyzpresets.json is now created if it doesn't exist.
=> Reworked XYZ presets interface

scripts/supermerger.py
Dev web-ui branch is now using a class object for output panel 
#322
=> Patch for issue #322, webui-dev branch

scripts/mergers/mergers.py, scripts/mergers/xyplot.py
=> #325 Fixed seed and xyz generation

scripts/mergers/xyplot.py, scripts/supermerger.py
=> Spell checking for Metadeta tab
